[package]
name = "nove"
version = "0.1.0"
edition = "2024"
authors = ["lokarex <lokarex@outlook.com>"]
description = "An easy-to-use, lightweight deep learning library wrapped around Burn Tensor."
license = "MIT OR Apache-2.0"
repository = "https://github.com/lokarex/nove"

[dependencies]
bincode = "2.0.1"
burn = { version = "0.19.1", features = ["train", "wgpu"], default-features = false }
rand = "0.9.2"

[dev-dependencies]
tempfile = "3.23.0"
