[package]
name = "nove_dataloader"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nove_tensor = { path = "../nove_tensor" }
nove_dataset = { path = "../nove_dataset"}
rand = { workspace = true }

[dev-dependencies]
nove = { path = "../nove" }